version: "1"

steps:
  build:
    image: cirrusci/flutter:stable
    commands:
      - flutter pub get
      - flutter analyze
      - flutter test
      - flutter build apk --release

  deploy:
    image: woodpeckerci/plugin-scp
    settings:
      host: 3.94.193.56
      username: ubuntu
      key: ${SCP_KEY}
      target: /home/ubuntu/builds/
      source: build/app/outputs/flutter-apk/app-release.apk
      port: 22
    when:
      event: push
      branch: main
