version: "1"

steps:
  login-ghcr:
    image: docker:20.10
    commands:
      - echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

  build:
    image: ghcr.io/harisali1412/flutter-ci:latest
    commands:
      - flutter pub get
      - flutter analyze
      - flutter test
      - flutter build apk --release

  deploy:
    image: alpine:3.18
    commands:
      - apk add --no-cache openssh-client
      - mkdir -p ~/.ssh
      - echo "${SCP_KEY}" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - scp -o StrictHostKeyChecking=no build/app/outputs/flutter-apk/app-release.apk ubuntu@3.94.193.56:/home/ubuntu/builds/
    when:
      event: push
      branch: main
