version: '1'

workspace:
  base: /flutter
  path: src

pipeline:
  setup:
    image: ghcr.io/cirruslabs/flutter:3.24.5
    commands:
      - flutter pub get

  analyze:
    image: ghcr.io/cirruslabs/flutter:3.24.5
    commands:
      - flutter analyze

  test:
    image: ghcr.io/cirruslabs/flutter:3.24.5
    commands:
      - flutter test

  build-web:
    image: ghcr.io/cirruslabs/flutter:3.24.5
    commands:
      - flutter build web --release --web-renderer html
    when:
      event: push
      branch: main

  docker-build-push:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_BUILDKIT=1
    commands:
      - echo "$${GHCR_TOKEN}" | docker login ghcr.io -u harisali1412 --password-stdin
      - docker build -t ghcr.io/harisali1412/flutter-web:latest .
      - docker push ghcr.io/harisali1412/flutter-web:latest
    when:
      event: push
      branch: main
