version: "1"

steps:
  build:
    image: flutter:stable  # Use official Flutter image
    commands:
      - flutter pub get
      - flutter analyze
      - flutter test
      - flutter build apk --release
