version: '1'

workspace:
  base: /flutter
  path: src

pipeline:
  setup:
    image: alpine:3.18
    commands:
      - apk add --no-cache flutter
      - flutter pub get

  analyze:
    image: alpine:3.18
    commands:
      - apk add --no-cache flutter
      - flutter analyze

  test:
    image: alpine:3.18
    commands:
      - apk add --no-cache flutter
      - flutter test

  build-web:
    image: alpine:3.18
    commands:
      - apk add --no-cache flutter
      - flutter build web --release
    when:
      event: push
      branch: main
