version: '1'

workspace:
  base: /flutter
  path: src

pipeline:
  setup:
    image: cirrusci/flutter:3.19.0
    commands:
      - flutter pub get

  analyze:
    image: cirrusci/flutter:3.19.0
    commands:
      - flutter analyze

  test:
    image: cirrusci/flutter:3.19.0
    commands:
      - flutter test

  build-web:
    image: cirrusci/flutter:3.19.0
    commands:
      - flutter build web --release
    when:
      event: push
      branch: main

  build-android:
    image: cirrusci/flutter:3.19.0
    commands:
      - flutter build apk --release
    when:
      event: push
      branch: main
