when:
  event:
    - push
  branch:
    - main

steps:
  build:
    image: gcr.io/kaniko-project/executor:latest
    commands:
      - /kaniko/executor --context $CI_WORKSPACE --destination=ghcr.io/${CI_REPO_OWNER}/${CI_REPO_NAME}:latest --dockerfile Dockerfile


  push:
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/${CI_REPO_OWNER}/${CI_REPO_NAME}
      tags: latest
      username: ${CI_REPO_OWNER}
      password: ${GHCR_TOKEN}

  deploy:
    image: appleboy/drone-ssh
    settings:
      host: ${SSH_HOST}
      username: ${SSH_USER}
      key: ${SSH_KEY}
      script:
        - echo "Deploying app on server..."
        - docker login ghcr.io -u ${CI_REPO_OWNER} -p ${GHCR_TOKEN}
        - docker pull ghcr.io/${CI_REPO_OWNER}/${CI_REPO_NAME}:latest
        - docker stop myapp || true
        - docker rm myapp || true
        - docker run -d --name myapp -p 9090:8080 ghcr.io/${CI_REPO_OWNER}/${CI_REPO_NAME}:latest
