when:
  - event: push
    branch: main

steps:
  - name: setup
    image: cirrusci/flutter:3.19
    commands:
      - flutter --version
      - flutter pub get

  - name: build-web
    image: cirrusci/flutter:3.19
    commands:
      - flutter build web

  - name: deploy
    image: alpine
    environment:
      SSH_KEY:
        from_secret: ssh_private_key
    commands:
      - apk add --no-cache openssh-client rsync
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - rsync -avz build/web/ user@your-server:/var/www/portfolio
