version: '1'

pipeline:
  setup:
    image: ghcr.io/cirruslabs/flutter:3.24.5
    commands:
      - flutter pub get

  analyze:
    image: ghcr.io/cirruslabs/flutter:3.24.5
    commands:
      - flutter analyze

  test:
    image: ghcr.io/cirruslabs/flutter:3.24.5
    commands:
      - flutter test

  build-docker:
    image: woodpeckerci/plugin-docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/harisali1412/flutter-web
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:7}
      username: harisali1412
      password:
        from_secret: ghcr_token
    when:
      branch: main
      event: push
